import { readFile, writeFile } from 'node:fs/promises';

// Shadow UMD module-system identifiers locally: Monaco's AMD loader must not
// turn this lazy browser dependency into an anonymous AMD module.
const source = await readFile('vendor/jszip.min.js', 'utf8');
await writeFile('jszip.min.js',
  '/* Generated by build-jszip.mjs from vendor/jszip.min.js. */\n' +
  '(function(define,module,exports){\n' + source.trim() +
  '\n}).call(globalThis);\n', 'utf8');
console.log('Built browser JSZip runtime (compatible with Monaco AMD loader).');
